### ISSUE TITLE
ImportError: cannot import name 'GeocoderClient' from 'ymaps'

### ISSUE THREAD

**Issue by axdget** [sfkan6/ymaps#1]
https://colab.research.google.com/drive/1iW5mnnRCkZHriGRhlw-B3u8K90XKWRNY#scrollTo=LpqXjMNdihE9

!pip install ymaps
from ymaps import *
from ymaps import GeocoderClient
client = GeocoderClient('01f38303-07e1-4b98-8d98-75ca1dd408a7')
client.geocode('Санкт-Петербург, ул. Блохина, 15')
#  https://pypi.org/project/ymaps/

ImportError: cannot import name 'GeocoderClient' from 'ymaps'
Подскажите в чем проблема?

**Comment by sfkan6** [comment]
Здравствуйте, проблема в [README.md](https://github.com/sfkan6/ymaps#readme), класс называется GeocodeClient.
